### ISSUE TITLE
Create a say hi video and put all say hi videos to a new md file 

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#29]
Create a new say hi video just like what others did. 
Examples
https://drive.google.com/file/d/1N73jeUk-p4QUFjNYIi6loCNL46NbUHaJ/view?usp=sharing
https://drive.google.com/file/d/1gyM0DKkxXyj39sFVeHNJ_G0rUq0kUuZT/view?usp=sharing

After recording, put all three videos into a md file named "say_hi_videos.md" under the root of this repo. 
In the future, all new moderators will be required to do the same video and put into this file.

**Comment by geopor** [comment]
In progress: https://github.com/tearust/moderators/blob/main/say_hi_videos.md

Still waiting for Google to process my video upload, then I can get the sharing link. Will update later.

**Comment by geopor** [comment]
Done. 
/img folder created in root of repo to hold necessary image assets.
