### ISSUE TITLE
write a new 2 minutes teaser doc

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#31]

**Comment by geopor** [comment]
New 2 Minute Teaser created https://github.com/tearust/tea-docs/commit/3dd17b2c7de54de30bd45303b9a92c80b0a4ccbe

**Comment by geopor** [comment]
Updated https://github.com/tearust/tea-docs/commit/b834333df7e0d4b5a18a7271fcd13bf146af3ecf

**Comment by geopor** [comment]
Updated with better distinction between layer-1 (BFT) and layer-2 (only needs to check for fail-stops). Also rearranged article to flow better and added headings  https://github.com/tearust/tea-docs/commit/dab479c5c065736fb73b5965797af4998d759089
