### ISSUE TITLE
write a short self introduction to your future andience in teaproject medium blog

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#32]
https://github.com/tearust/tea/blob/master/social_account.md has the account information you will need.
Write a short intro, telling your future audience who you are, and what you are supposed to tell in the teaproject medium blog.

**Comment by geopor** [comment]
Done: https://teaproject.medium.com/a-short-introduction-from-a-new-team-member-3fbb4d743587

**Comment by kevingzhang** [comment]
as I mentioned rule no. 1, do not close issue unless it was created by yourself.
