### ISSUE TITLE
after #32, write your first medium blog. Your first impression of TEA

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#33]
This is a follow up task after #32 .

After our long introduction meeting, what is your first impression of TEA. Write it as a blog. post to medium.

It doesn't have to be long. It it needs to be long, try to separated it into several blogs. Make them a series "First impression series".

**Comment by geopor** [comment]
Done: https://teaproject.medium.com/first-impression-of-tea-series-1-97bf95d2ff9b

**Comment by kevingzhang** [comment]
Very good article, just do not close it by yourself
