### ISSUE TITLE
install node.js and run your local website server so that you can preview the tea-docs locally without deploying to the internet

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#38]
Try it again on your new macbook air. If there are any problem, let me know, I am happy to help you. 
Once it is running without problem, send this issue back to me. I will close it

**Comment by geopor** [comment]
`brew install node`

Using the commands here: https://github.com/tearust/website
1. The backend is started.
2. The frontend has a dependency issue. 
<img width="584" alt="npm frontend error" src="https://user-images.githubusercontent.com/86096370/126208054-eee5dff9-29ca-4430-a204-f3d6f4a6344a.png">
The `npm i` step results in the following error:

> Could not resolve dependency:
>npm ERR! peer eslint@">=1.6.0 <7.0.0" from eslint-loader@2.2.1
>npm ERR! node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader
>npm ERR!   eslint-loader@"^2.2.1" from @vue/cli-plugin-eslint@4.5.6
>npm ERR!   node_modules/@vue/cli-plugin-eslint
>npm ERR!     dev @vue/cli-plugin-eslint@"4.5.6" from the root project

**Comment by kevingzhang** [comment]
I would suggest you to do the following steps. Try one step, if doesn't work, then move on to the next step.

1. Lower your node version to node v14.12.0. this is the version I am using. You are likely using Node V16 which is not supported by VUE yet. This could be the main reason.
2. make sure typescript is installed  https://www.npmjs.com/package/typescript
3. clean up local npm cache by run ' rm -rf node_modules/ ', then npm i again for a refresh install
4. Install vue by run ' npm install vue  '
let me know if any of the steps above works

**Comment by geopor** [comment]
Step 1 worked, I can see the local website repo at localhost:3000. This was the exact process:
`node -v`
> v16.5.0

Install node v14:
`brew unlink node`
`brew install node@14`

Update PATH:
`echo 'export PATH="/opt/homebrew/opt/node@14/bin:$PATH"' >> ~/.zshrc`
`source ~/.zshrc`

`node -v`
> v14.17.3

**Comment by kevingzhang** [comment]
Awesome. you can close if this issue has been fixed. Please continue run your local website and verify the tea-docs. including the t= sign
