### ISSUE TITLE
Commons stack using such online form to gather potential investors(supportors), do you think we can do the same?

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#39]
https://commonsstack.org/apply

I am reading Commons stack today. It is a typical bonding curve project. 
I am reading https://medium.com/giveth/introducing-the-commons-stack-scalable-infrastructure-for-community-collaboration-6886eb97413e  and noticed that they are gathering whoever is interested in Commons Stake using such a form on their website.

I am thinking should we follow this idea? Write a wonderful article, and receive leads and grow our supporters' community?

**Comment by kevingzhang** [comment]
![image](https://user-images.githubusercontent.com/1761809/126079692-6a24b548-a457-4521-881f-117f4733fbfc.png)

**Comment by geopor** [comment]
Introducing TEA Project

## Problem that TEA Project solves.

## Why TEA Project Solves the Problem
- Trust as a Service model
- Explain how decentralized nodes (miners) can be trusted

## T Token and Camellia
- Distribution model / explain the importance of Camellia.
- Miner and staker incentives.

## Why TEA Project is so important
- Chance to persuade others why TEA Project is important.
- Privacy issues related to personal data.
- Cybersecurity - threat surface for cyber attacks keeps growing larger.

## How to Get Involved
- Engineers.
- Early-stage investors.
- Social media influencers.
- Community managers.

**Comment by geopor** [comment]
Please see outline above and let me know if you want any changes before I write the article. Especially the last section - are there any other groups we should target?

The application form Commons Stack is using is done using Typeform. Did you want the same, or something simpler like a Google Form?

**Comment by kevingzhang** [comment]
No need to start working on the outline yet. I am just asking do you think this method is worth our effort.  The outline is good to me.

**Comment by geopor** [comment]
Ok I will add this to my content calendar. I think timing for it should be right after website is more polished as many will want to visit the website after learning of the project. Social media marketing should include privacy-focused groups as we are aligned with their goals.

**Comment by kevingzhang** [comment]
Agreed.
