### ISSUE TITLE
Paul - Introduction video creation for investors.

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#4]
Remember to log the time you spend on this task

**Comment by kevingzhang** [comment]
this issue has been under your name for 7 days.

**Comment by paulm0920** [comment]
Hi Kevin, here is the intro video: 

https://drive.google.com/file/d/1gyM0DKkxXyj39sFVeHNJ_G0rUq0kUuZT/view?usp=sharing

**Comment by kevingzhang** [comment]
Pleas note how many hours or minutes you spent on this small task. Thanks
