### ISSUE TITLE
Bi weekly report for by the end of this week

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#41]
This week, we should send out a bi-weekly report to the first round investors. So please prepare such a report including mostly what we did during the two weeks on the marketing side. i will prepare the technical and product side

**Comment by kevingzhang** [comment]
Please give my your planned deadline for this.

**Comment by geopor** [comment]
I will take to you more about this tomorrow and should have it for you by Thursday night.

**Comment by geopor** [comment]
Polkadot Link asked for a deck in PDF format. It would be helpful to see other marketing decks to see how other projects are presenting themselves.

**Comment by kevingzhang** [comment]
shared with you our current pitch deck in google drive

**Comment by kevingzhang** [comment]
also emailed you about the content we supposed to add to this bi weekly report

**Comment by geopor** [comment]
# Polkadot Link Pitch Deck
Outline of what's to be worked on
- Some editing of existing deck ( all will be saved to a new deck w version \#)
- Issues that were raised in other issues involve the pitch deck, will be edited accordingly https://github.com/tearust/moderators/issues/43#issuecomment-885272040
- RafTEA details will be added

## User growth strategy
Polkadot Link is asking for a marketing-centered pitch deck, so the marketing & user-acquisition aspect of the deck needs to be expanded upon.

Show that TEA Project has an effective strategy to
1) Build a network effect
2) Monetize the large network effect

### Incentivize Participation
- Incentivize early user through liquidity mining, to give equity to early adopters.
- Answer the following question: How will the economic system drive value to all participants who come on board?

**Comment by geopor** [comment]
Pitch Deck, version 1.

Getting late and nearly finished, just need to add tokenomics page + team page.

@kevingzhang Any suggestions on how to introduce RafTEA, this is a Pitch Deck so I worry about going too in-depth.

Please provide any feedback, consider this a first draft:

[TEA Project Concise Pitch Deck v1.pdf](https://github.com/tearust/moderators/files/6884574/TEA.Project.Concise.Pitch.Deck.v1.pdf)

**Comment by geopor** [comment]
![Screen Shot 2021-07-27 at 3 25 35 AM](https://user-images.githubusercontent.com/86096370/127139047-51bca470-4ad6-4949-ae7f-d8748fd34030.png)

Page 14 updated w missing column, will make it into next update

**Comment by geopor** [comment]
Polkadot Link pitch deck completed and sent.

Weekly report follows:

**Comment by geopor** [comment]
## TEA Project Team Updates
### New Full-Time Team Member

The TEA Project welcomes our 4th full-time team member, George Pornaras. George is a content marketer who has broad experience across TEA's tech stack including cloud computing and GPU mining. He'll be working on updating the Teaproject.org website and promoting the TEA Project through social media.

### New Community Moderators

We have 3 part time moderators who have joined our community.

[Al Lakhani (intro video)](https://drive.google.com/file/d/1N73jeUk-p4QUFjNYIi6loCNL46NbUHaJ/view)

[Naveen Kandwal](https://in.linkedin.com/in/naveenkandwal89)

[Paolo Montesclaros (intro video)](https://drive.google.com/file/d/1gyM0DKkxXyj39sFVeHNJ_G0rUq0kUuZT/view?usp=sharing)

You can chat with them on our Telegram group where they'll be active promoting useful posts and encouraging discussion about the TEA Project.

## TEA Project Social Media Links

We've now completed setup of our social media profiles:

- [YouTube](https://www.youtube.com/channel/UChYmd52JIe0zTdIdXHLK7WQ)
- [Twitter](https://twitter.com/teaprojectorg/)
- [Instagram](https://www.instagram.com/teaprojectorg/)
- [Reddit](https://www.reddit.com/user/teaprojectorg/)
- [Medium blog](https://teaproject.medium.com)
- [Telegram](t.me/teaprojectorg)

Our goal at this early stage is to increase outreach to the crypto community by publishing engaging content about the TEA Project. Our initial focus will be regular weekly posts to our Medium blog and increasing the number of explainer videos on our YouTube channel. 

# Preview of the TEA Browser Wallet Released

Preview 1 of the TEA Project's browser wallet is live at https://http://68.183.182.174/. In addition to the typical wallet functions of storing tokens, users can also mine their CML and stake both CML and TEA. There's also a marketplace built into the wallet to allow CML sales. 

We're especially looking to onboard miners as they will form the backbone of the TEA network. To reach this goal, we're preparing a mining contest in August. The miners who mine the most tokens during the competition will receive rewards, possibly USDT or CML.

To learn how to start earning revenue with the TEA browser wallet, check out our [mining & staking tutorial](https://teaproject.org/#/doc_list/Try_the_demo%2FREADME.md) which includes a video tutorial.

# Website Upgrade

The website is getting refreshed over the next few weeks to better reflect the status of the TEA Project. As our underlying tech evolves, the documentation needs to be updated to properly reflect TEA Project updates. This emphasis on clarity will help more users who visit our site understand the benefits of using the TEA Project. 

Some of these updates also include: 

- A new intro video at the top of the homepage.
https://www.youtube.com/watch?v=DSmnP_kgcig

- A new TEA Project logo.
https://github.com/tearust/tea-browser-wallet/blob/master/public/tea_logo/logo1.png

# Introduction to the 2nd TEA Project Phase: RafTEA

RafTEA is the 2nd phase of TEA Project's development. The first phase was called "T-rust" and focused on the trust platform and the mining portal. The RafTEA phase is focused on TApps ecosystem, an investment platform. Being able to use Raft consensus on our layer-2 is an important technical milestone. You can read more about the technical details of our implementation of Raft [here](https://github.com/tearust/moderators/blob/main/RafTEA/README.md).

# Preparing for the Series A Funding Round
With our seed round completed, we now turn to securing our Series A funding round. We're updating content important to investors (pitch deck, whitepaper, website documentation) to properly reflect an evolving TEA Project. We are aiming to apply for the Series A funding round in early August.

# Looking Forward to Preview 2
Besides what we have already shown in the first preview, we'l be adding a bonding curve-powered TAppStore. The TAppStore allows for revenue sharing, investment, and hosting tApps plus a traditional app store.

**Comment by kevingzhang** [comment]
Can you either put the md file somewhere and link to me, or email me the MD file as attachment. By doing so I can easier send to our investors

**Comment by geopor** [comment]
Here it is. I'll put future updates in the Blog folder as well.

https://github.com/tearust/tea-docs/blob/main/Blog_and_Vlog/Bi-Weekly%20Report%20-%2007-29-21.md
