### ISSUE TITLE
Write the tutorial of Preview1

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#42]
This is for the external tester whoever want to try the preview 1. 

We also need a tutorial video. That is not only for the external testers, but also show to the investors who may not be interested get their hands dirty to try on their own.

The tutorial contains text and video.

it is part of the new website.

Please give me an ETA.

I hope all of the new website can go live by the end of this week.

**Comment by geopor** [comment]
Working on tutorial video and writeup, will work on updating the wallet's **Welcome** page at the same time. ETA = end of today, 7/23.

They testers will have to import test accounts, are the previewers going to use the same dummy accounts?
https://github.com/tearust/tea-camellia/blob/main/tests/batch_exported_account_asdfasdf.json

**Comment by kevingzhang** [comment]
No. There will required to fill up a Google form with their own polkadot
account. See the preview 1 design in moderators repo

**Comment by geopor** [comment]
Done including requested revisions based on last commit's comments https://github.com/tearust/tea-docs/commit/0ba9794860630c095e636c343e27334d718fdd34

The video and README can be updated as the wallet functionality changes before the contest launches.
