### ISSUE TITLE
change requests for the 2nd intro video

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#43]
https://drive.google.com/file/d/1xSaroQ42aTjaI_IdY9cdICmgz7kqP2cO/view?usp=sharing
this is the link to the video.

Change requests:
1. The first sentence "TEA Project is a decentralized cloud computing platform that hosts rich", I cannot hear the word "Host" which is very important. Please ask them to make sure the word "host" can be heard.
2. Still the first sentence " ...also known as "Rich dApps.". I hope the words "Rich dApps" can be shown on the screen , because we should emphasize it to the audiences. They probably never heard such a new word and won't know how it is spelled.
3. at 1:25 - 1:29. I hope to see those 4 key concepts written on the screen. Many audiences are not familiar with those new technologies terms, so it would be better show the words rather just "say" them.
4. at 1:22, we should change to a new page, since the concept we are talking about after 1:22 is not related to the previous page.
5. at 1:30, we should change a to new page too. 
@waaghree and @geopor , please also add your comments and request to change too.

**Comment by geopor** [comment]
:23 "apps with similar scalability and user experience .." It fades to a white screen at this point. It would be a good opportunity to showcase what a rich app looks like

1:05 -1:22 "verify the execution environment where the code runs" - The hand is coloring in a wheel here, and the consensus graphic isn't great. I just don't feel the motion graphics here help explain anything.

<img width="986" alt="Screen Shot 2021-07-22 at 3 11 47 PM" src="https://user-images.githubusercontent.com/86096370/126716108-f6b5c923-2a74-4b18-9e95-d51f47e0698e.png">

2:01 - The text at the top has some grammatical / clarity errors. I suggest that the font should be made a bit bigger to be more readable as well as the following edits:

Decentralized but
• Small number of rich applications
• Needs special privacy protocol
• Poor performance

Run rich applications with high performance but
• Centralized
• Potential privacy breaches
• Censorship

**Comment by geopor** [comment]
I think this can be closed @lxm218 
New edited video uploaded here: https://www.youtube.com/watch?v=DSmnP_kgcig
