### ISSUE TITLE
UI Issues for wallet

### ISSUE THREAD

**Issue by geopor** [tearust/moderators#44]
<img width="1033" alt="Screen Shot 2021-07-21 at 12 09 10 AM" src="https://user-images.githubusercontent.com/86096370/126454603-63a904ae-26cf-4360-a96e-0d6a7b969e03.png">

• "Staker" column cuts off full address.
• Possible to place T token logo instead of "TEA" in "Staking with" column?

**Comment by geopor** [comment]
<img width="897" alt="Screen Shot 2021-07-21 at 12 26 48 AM" src="https://user-images.githubusercontent.com/86096370/126454866-7cb8948d-d080-451d-9271-37b88a2f7dbe.png">

• Text should read: You can either stake 1000 TEA or one defrosted CML to a staking slot. You should leave "Staking with CML" empty if you're staking with TEA.

• "Acceptable slot index" should read "Slot index choice"

**Comment by geopor** [comment]
<img width="1165" alt="Screen Shot 2021-07-21 at 12 34 25 AM" src="https://user-images.githubusercontent.com/86096370/126455563-865d7048-7648-4b91-872a-928d1b201b71.png">

• Text should read: Withdrawing reward not allowed with staking debt balance.
• UI issue: If someone clicks **Withdraw reward**, then it would be nice to default to asking if they'd like to pay off debt if they aren't allowed to withdraw with a debt balance.

**Comment by geopor** [comment]
<img width="754" alt="Screen Shot 2021-07-21 at 12 35 01 AM" src="https://user-images.githubusercontent.com/86096370/126456120-5b0c8ff0-9e25-4876-a1b9-4047d48dc690.png">

• Popup after clicking **Pay off debt**. It should read: 
Are you sure you want to pay off your debt in full? If your balance doesn't cover your entire staking debt, the transaction will be cancelled.

**Comment by geopor** [comment]
<img width="1135" alt="Screen Shot 2021-07-21 at 12 46 28 AM" src="https://user-images.githubusercontent.com/86096370/126456892-98144d66-f79e-4580-b3c1-b4c4b0f487d8.png">

• Popup says **Staking invest**. I think it should just say: Stake

**Comment by geopor** [comment]
<img width="909" alt="Screen Shot 2021-07-21 at 12 47 34 AM" src="https://user-images.githubusercontent.com/86096370/126457177-098799ac-4e36-46e2-9ee5-78303d3aa61e.png">
• Instead of highlighted text, should read something like:
- Auction CML
- Auction off CML
- Auction your CML

**Comment by geopor** [comment]
<img width="425" alt="Screen Shot 2021-07-21 at 12 48 43 AM" src="https://user-images.githubusercontent.com/86096370/126457418-8221a545-188f-447a-aa05-3eac4901d670.png">
 
• Text should read:
After unstaking, your slot will be taken by the user whose staking slot is currently above you.

**Comment by geopor** [comment]
<img width="1106" alt="Screen Shot 2021-07-21 at 12 49 43 AM" src="https://user-images.githubusercontent.com/86096370/126457957-c2df0660-ff05-49fc-be49-527657781e82.png">

• Text should read:
The following are the remaining genesis block Camellia seeds. You can claim a seed by using a coupon.

**Comment by geopor** [comment]
<img width="907" alt="Screen Shot 2021-07-21 at 12 51 25 AM" src="https://user-images.githubusercontent.com/86096370/126458374-25d1ea61-a4e0-401c-ac7e-e6546fdde7d4.png">

• Error message is vague - because I was trying to start an auction it shouldn't matter how much money I have so I think this is a backend logic error (I had 70 T at the time, and the wallet didn't let me start an auction with a minimum bid of 101). 
• Text should read (in case it is a bidder who doesn't have enough funds): Not enough balance to bid.
• Text should read (in case it is the seller who doesn't have enough funds, if this is what is truly intended): Not enough balance to start an auction.

**Comment by geopor** [comment]
<img width="1126" alt="Screen Shot 2021-07-21 at 12 53 14 AM" src="https://user-images.githubusercontent.com/86096370/126459263-02792006-d281-4497-8407-8bdefe6e4515.png">
 • Instead of **Put CML to auction store**, should read:
Put CML up for auction
• Instead of **You have to pay off your debt before adding CML to marketplace.**, it should read:
You have to pay off your debt before adding CML to the marketplace.

**Comment by geopor** [comment]
<img width="1113" alt="Screen Shot 2021-07-21 at 12 57 54 AM" src="https://user-images.githubusercontent.com/86096370/126459766-9d9ecfcc-569a-49fa-ae8b-5c1a07464f00.png">

• After clicking **View Bid List** this pops up:

<img width="904" alt="Screen Shot 2021-07-21 at 12 58 15 AM" src="https://user-images.githubusercontent.com/86096370/126459996-edeecac9-38bf-439d-801d-b5afedc37d69.png">

• It should just read:
Bids

**Comment by geopor** [comment]
<img width="904" alt="Screen Shot 2021-07-21 at 12 59 33 AM" src="https://user-images.githubusercontent.com/86096370/126460171-0f9f1215-47d0-46d8-a771-ed4a9be84d24.png">

• Should read:
You need at least 101.0000 TEA to bid on this auction.

**Comment by geopor** [comment]
<img width="1004" alt="Screen Shot 2021-07-21 at 1 01 58 AM" src="https://user-images.githubusercontent.com/86096370/126460509-e0804b5a-3578-4699-868d-254ec21ed631.png">

• Under Auctions column, should read:
Bid

**Comment by geopor** [comment]
<img width="943" alt="Screen Shot 2021-07-21 at 1 02 37 AM" src="https://user-images.githubusercontent.com/86096370/126460629-43d8d227-ec11-486b-99cf-34a458d6bc67.png">

• Edge case .. end of epoch occurred while dialog box was up. Rejected bid because auction ended. The error message should read:
Auction does not exist.

**Comment by geopor** [comment]
<img width="975" alt="Screen Shot 2021-07-21 at 1 04 45 AM" src="https://user-images.githubusercontent.com/86096370/126460964-d9ca93f8-c96f-47af-9bd7-62a7da636dff.png">

• In Auctions column, should read:
Add

**Comment by geopor** [comment]
<img width="904" alt="Screen Shot 2021-07-21 at 1 05 01 AM" src="https://user-images.githubusercontent.com/86096370/126461095-94991676-19c5-49ac-a519-e0117d7f247f.png">

• This is confusing. The price is currently 101, better UI would be to say directly "you need to bid at least 102" like how eBay does it. But even if it's going to be kept this way where the user must do the math in their head, it should read:
You need add at least 1.0000 TEA to your existing bid.

**Comment by geopor** [comment]
I noticed at least 3 different modal "success" popups, and the consistent issue is that the first letter should be capitalized and there should be no period at the end for a modal pop-up that flashes like this.

<img width="887" alt="Screen Shot 2021-07-21 at 12 56 20 AM" src="https://user-images.githubusercontent.com/86096370/126461844-e7eb73a1-abf6-4e8b-bfff-df4d7ec60409.png">
• Above dialog should read:
Success

<img width="1150" alt="Screen Shot 2021-07-21 at 1 00 40 AM" src="https://user-images.githubusercontent.com/86096370/126461939-e93fcc7c-263d-41da-b56c-850526d22290.png">
• Above dialog should read:
Copied

**Comment by kevingzhang** [comment]
> <img alt="Screen Shot 2021-07-21 at 12 09 10 AM" width="1033" src="https://user-images.githubusercontent.com/86096370/126454603-63a904ae-26cf-4360-a96e-0d6a7b969e03.png">
> 
> • "Staker" column cuts off full address.
> • Possible to place T token logo instead of "TEA" in "Staking with" column?

@liyangwood , we can use ... in the address which does not fit the width. Since people just need to click the link without read the full text.

**Comment by liyangwood** [comment]
fixed.
Will assign back to test after deploy with wallet version 0.0.8

**Comment by kevingzhang** [comment]
You can assign back to @geopor for testing once deployed.

**Comment by liyangwood** [comment]
deployed

**Comment by kevingzhang** [comment]
@geopor Please verify the fixes, and close when done. If you have other new change requests, please create new issue

**Comment by geopor** [comment]
Most are done, will close this and open issues separately for what's left
