### ISSUE TITLE
UI issue for wallet - Auctions

### ISSUE THREAD

**Issue by geopor** [tearust/moderators#46]
<img width="1191" alt="Auction - Add to Bid" src="https://user-images.githubusercontent.com/86096370/126692404-d7f03d40-e3a6-4781-a766-875b93099f9b.png">

• Hover over "+" symbol should read:
Increase Bid

<img width="900" alt="Auction - Amount to increase bid" src="https://user-images.githubusercontent.com/86096370/126692406-aff4cd90-20bb-4877-a126-c97afce0072a.png">

1. Should read:
You need to add at least __ TEA to your existing bid.

2. Should read:
Amount to increase bid

<img width="1056" alt="Auction - Bid" src="https://user-images.githubusercontent.com/86096370/126692408-fbfe0a48-c141-4b73-8d58-c2e74d71aa5b.png">

• Should read:
Bid

<img width="1112" alt="Auction - Buy now price " src="https://user-images.githubusercontent.com/86096370/126692410-05140cfb-f2f6-468c-9b8d-4cc4170e9c2f.png">

• Should read:
Buy now price

**Comment by liyangwood** [comment]
fixed
Pls test after deployed wallet version: 0.0.9

**Comment by liyangwood** [comment]
deployed

**Comment by geopor** [comment]
<img width="650" alt="Screen Shot 2021-07-23 at 2 39 45 PM" src="https://user-images.githubusercontent.com/86096370/126844550-ec0e9975-e5e6-4e2c-8435-b7d7dedf44de.png">

• Sidebar should read the same as the heading: 

Auction list

<img width="569" alt="Screen Shot 2021-07-23 at 2 39 53 PM" src="https://user-images.githubusercontent.com/86096370/126844552-752ab5a6-29a4-4b66-b75c-275e1168b1f8.png">

• Both sidebar and heading should read:

My auctions

<img width="589" alt="Screen Shot 2021-07-23 at 2 40 02 PM" src="https://user-images.githubusercontent.com/86096370/126844553-ccbab9d1-92df-463b-9c71-e0c3aeae78ea.png">

• Both sidebar and heading should read:

My bids

**Comment by geopor** [comment]
<img width="1024" alt="Screen Shot 2021-07-23 at 2 40 42 PM" src="https://user-images.githubusercontent.com/86096370/126844555-c0eda852-1414-4222-8f88-03844ea5f71f.png">

• (Popup for Bids button on an active auction)  Should read:

Active bids

**Comment by liyangwood** [comment]
fixed
Pls test after deployed wallet version: 0.0.10

**Comment by liyangwood** [comment]
deployed
