### ISSUE TITLE
UI issue for wallet - T vs TEA vs Icon

### ISSUE THREAD

**Issue by geopor** [tearust/moderators#48]
<img width="1033" alt="Screen Shot 2021-07-21 at 12 09 10 AM" src="https://user-images.githubusercontent.com/86096370/126694434-659c0481-8a5d-4945-b831-fada36b4b8d9.png">
<img width="897" alt="Screen Shot 2021-07-21 at 12 26 48 AM" src="https://user-images.githubusercontent.com/86096370/126694446-a4166fbf-f500-4787-a094-11c54c876d86.png">
<img width="904" alt="Screen Shot 2021-07-21 at 12 59 33 AM" src="https://user-images.githubusercontent.com/86096370/126694449-ace5b7ac-f255-4ba6-9599-c6c8376889fc.png">

It looks like we are referring to the token as **TEA** throughout the UI (see pics above). I thought the actual token is called **T**, or referred to as **T token** or the symbol 
<img width="35" alt="Screen Shot 2021-07-22 at 11 58 14 AM" src="https://user-images.githubusercontent.com/86096370/126694685-551e8a03-2893-49cd-8397-2fa8abfdeb7e.png">

**Comment by kevingzhang** [comment]
US Dollar is TEA Token
$ is t= sign
USD is TEA

Use these concepts when they appear in the UI.

**Comment by kevingzhang** [comment]
Do not assign issue to more than one people. There would be always ONE person who is responsible to push the issue forward
