### ISSUE TITLE
UI issue for wallet - staking slot

### ISSUE THREAD

**Issue by geopor** [tearust/moderators#49]
<img width="901" alt="Staking - why slot index choice" src="https://user-images.githubusercontent.com/86096370/126694956-31ef20da-af76-400f-a29c-89c70916b647.png">

Why do we allow people to choose the staking slot? Shouldn't they automatically be assigned the best (lowest) slot available?

**Comment by kevingzhang** [comment]
This is an important concept but we do not know how to explain in human language.

This is not the Slot index, it should be the buffer. 

The system will automatically choose the best slot for you, but, in the distributed system, there would be several users compete for the same best position, for example slot No. 2 are completed by 3 users in the same block. Of course, only the first one will win No. 2. So now there is the problem: Will user 2 be OK with No.3 slot or not? This is what the buffer means here. If the user 2 fill in 0, that means no buffer, no tolerant, no flexibility. so if user 2 did n to win slot 2, his request would be cancelled. 

Please let us know what is the best way to explain this. of course, the current text is incorrect.

**Comment by kevingzhang** [comment]
Also always name the issue with meaningful title.

**Comment by geopor** [comment]
Uniswap uses the term **slippage**. Users set a slippage percentage and if the price rises/falls beyond that percentage while waiting for the tx to complete the order is cancelled.

My suggestion:

Instead of **Slot index choice**, it should read:
Max allowable slippage

It may need a tooltip to explain, so I'd suggest the following tooltip:
The system will try to choose the best slot available but multiple users might be competing for the best available staking slot. **Max allowable slippage** indicates how many levels you're willing to fall and still have your staking transaction executed. Selecting *0* means you only want to stake at the currently available slot with no allowable slippage.

**Comment by kevingzhang** [comment]
@liyangwood Please follow @geopor suggestion on the text and tip

**Comment by liyangwood** [comment]
fixed.
Test after deployed with wallet version: 0.0.9

**Comment by liyangwood** [comment]
deployed.

**Comment by geopor** [comment]
<img width="849" alt="Untitled 2" src="https://user-images.githubusercontent.com/86096370/126846239-f8bd5b3c-560b-4e49-b5d5-54d518b1b726.png">

1. If there's no tooltip, is there any way for the text to only show on hover? (see pic above)
2. I've shortened the text a bit, please update to the following:

Select how many levels you're willing to fall and still have your staking transaction executed if others are competing for a slot. Selecting 0 means you only want to stake at the currently available slot with no allowable slippage.

**Comment by kevingzhang** [comment]
tooltip is good. If it is too long to fit into the tootip, we can have a "?" link to our tea-docs URL directly to our website. If so, please also write a doc and give the link to Jacky  @geopor

**Comment by liyangwood** [comment]
![Screen Shot 2021-07-24 at 11 20 03 AM](https://user-images.githubusercontent.com/3214173/126855958-9171be7c-db0b-483a-876b-856c2a059aa7.png)

Tooltip as above.

**Comment by kevingzhang** [comment]
if the tooltip is that long, why do not we just write the text in the UI directly?

**Comment by geopor** [comment]
@kevingzhang  We only want people to see it if they are confused, otherwise it would be distracting.

@liyangwood I made the text shorter above, you can change it to this:

Select how many levels you're willing to fall and still have your staking transaction executed if others are competing for a slot. Selecting 0 means you only want to stake at the currently available slot with no allowable slippage.

**Comment by liyangwood** [comment]
fixed with wallet version 0.0.11
