### ISSUE TITLE
Telegram group is missing an official group name

### ISSUE THREAD

**Issue by geopor** [tearust/moderators#50]
I chatted with Naveen and this is the only invite link he can get for our Telegram group: https://t.me/joinchat/-IjpcwxlZbZmOWUx

I suspect our group is an ordinary group and not a supergroup. Once we are a supergroup we can get an official name and share a much better looking link, for example https://t.me/cardano

To upgrade to supergroup and set the name, it has to be done by the group owner. Here are the instructions I found:

1. Go to the group management screen for the group
2. Select "Edit Group"
3. Select "Group Type"

![edit_group_type](https://user-images.githubusercontent.com/86096370/126846546-f415613b-407b-4556-9912-297d8122faa4.png)

4. Set a public username for the group

![set_group_username](https://user-images.githubusercontent.com/86096370/126846545-6acbaa1d-dbae-41c3-a295-4fa49d41e767.png)

5. Save your changes and that group will be automatically upgraded to a supergroup by Telegram.

After it is done, please leave the official name of our Telegram group here in the comments and I will add it to our social accounts list.

**Comment by kevingzhang** [comment]
I promoted you as a new admin, you can do whatever you want now. Please do so and close the issue when you done

**Comment by geopor** [comment]
To upgrade to supergroup and set the name, it has to be done by the group owner.

**Comment by kevingzhang** [comment]
done, t.me/teaprojectorg. because t.me/teaproject has been occupied by someone else
