### ISSUE TITLE
Please check for the new pay off modal.

### ISSUE THREAD

**Issue by liyangwood** [tearust/moderators#51]
![Screen Shot 2021-07-24 at 10 56 27 AM](https://user-images.githubusercontent.com/3214173/126857581-50d0c7dd-23e6-467e-aa08-b7ed365c0cb5.png)

According the latest layer1 logic. user need to select the cml to pay off in above modal.
please review it for any changing needed.

**Comment by geopor** [comment]
Instead of ** Pay off cml id**, it should read

CML ID to pay off

**Comment by liyangwood** [comment]
fixed with version 0.0.12

**Comment by geopor** [comment]
Looks good
