### ISSUE TITLE
Depends on #54. When video is completed, make a blog post including the video to website and medium

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#56]
Please wait for the video completed in #54.  Please also review the progress of this video during production. there should be multiple revisions.

**Comment by geopor** [comment]
- Posted to Medium: https://teaproject.medium.com/how-devs-miners-and-consumers-together-support-the-tea-token-economy-d162b9c170cc
- Video added to existing content on website to better explain the topics touched on in the article.
- Posted to the Twitter account.
- YouTube, Twitter, and Medium links posted to Telegram moderators group encouraging them to post to their socials.
