### ISSUE TITLE
Translate #53 to Chinese. Miner tokenomics 

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#59]
You can write a md file in the moderator repo , or just go to the tea-docs under the Chinese folder.

**Comment by kevingzhang** [comment]
You can find the issue #53

**Comment by lxm218** [comment]
TEA 项目的矿工主要对加入网络的收益感兴趣。如果我们将 TEA 项目和云计算类比为优步和汽车，您可以说 TEA 项目需要用优步激励车主开车的方式来激励其矿工。没有中心化的公司来支付工资或拥有挖矿节点，精心设计的代币经济就必须让矿工对奖励有足够的兴趣，以使其硬件与网络保持联系。 TEA 项目的代币经济计划有助于保持网络平稳运行并创造足够的投机来促进增长。
 
除了TEA项目的底层技术，矿工最关心的是他们的投资回报率，即下面两个问题：
给以特定的硬件、维护和时间成本，我可以挖到多少TEA代币？
TEA代币价格是否会上涨或者至少可以合理地维持其价值？
矿工们会很高兴地发现 TEA 项目挖矿不需要强大的硬件。与其他加密货币挖矿项目相比，TEA 项目非常绿色环保- 它不需要消耗大能量的强大处理器，也不需要 TB 级硬盘空间才能达到的大量输出需求。 TEA 矿机可以是小型、廉价的物联网机器。这样的系统设计使得大多数矿工可以负担得起硬件费用。大部分挖矿成本来自 Camellia NFT。
矿工必须通过公开拍卖购买Camellia。当新的Camellia产生并通过竞价出售时，DAO 会烧掉竞价者支付的 TEA。由于种子的供应受到严格控制和限制，Camellia 的价格会上涨，TEA 代币的价格也会上涨，因为矿工需要TEA来购买种子。矿工想要购买Camellia是因为开采 TEA 有利可图，这是另一个保持 TEA 价格上涨压力的正循环。
DAO常规性销毁TEA代币会增加供应冲击，这有助于稳定 TEA 的价格。矿工用TEA 代币换取Camellia，这些TEA代币将被销毁，Camellia被种植到矿机中时需要时间来生长。此外矿工需要等待Camellia成熟后挖矿收益逐步增长，所以早期矿机的 TEA 代币收益率相对较低。
由此我们可以看到 TEA 代币的流通是如何变成无限循环的：
矿工购买更多的Camellia来进行更多的挖矿；
DAO 会销毁矿工为购买Camellia支付的 TEA；
矿工等待他们种植的Camellia成熟并生产更多的 TEA 代币，这些代币可用于购买更多的Camellia。
我们想看到这个无限循环的工作，但它仍然需要一种冷启动的方式。在 TEA 项目开始时，实际上还没有什么可以启动这个循环：TEA 区块链中没有 TEA 代币，只有冷冻的Camellia。 Camellia NFT 的解冻计划由一种算法控制，因此在开始时很少部分解冻。这少数幸运的解冻Camellia属于早期投资者，他们将通过种植解冻的Camellia开始挖矿，于是有一些 TEA 进入了 TEA 系统。因为种植的Camellia需要时间来生长，矿工开始以相对较低的收益率挖到 TEA。此时的 TEA 供应量很少，所有 TEA 代币所有者都是早期投资者。我们可以负责任地假设他们知道 TEA 和 Camellia 的价值，否则他们也不会投资 TEA 项目。就像早期的房地产投资者争相购买规划开发区域周围的土地一样，这些早期投资者在项目的早期阶段就积累了宝贵的资产。由于他们知道 TEA 项目的价值，因此他们不太可能在公开市场上倾销 TEA。
相反，这些早期投资者极大可能会将挖矿收益的 TEA代币投资到其他矿工机器的staking 位置，并购买更多的Camellia来启动更多的挖矿节点。他们投资 TEA 的动机是占据最好的 staking 位置，随着时间的推移，这些位置会变得越来越稀缺。如果大部分早期的 TEA 代币被再投资，那么市场上的供应就会有限。毫无疑问，在这种可能的情况下，TEA 的价格会被抬高，更不用说早期投资者可能有很多钱从市场上购买更多的 TEA 代币。
有趣的是，如果 TEA 价格上涨，种植Camellia作为一项业务的利润就越高。如果 Camellia 种植有利可图，那么更多的矿工可能会想要进入Camellia种植，但他们需要 TEA 来购买Camellia。因此，TEA 代币价格将受益于更多矿工的加入。
这一切听起来很不错，但你可能想知道如果 TEA 代币持有者开始抛售他们的资产会发生什么？现在矿工和早期投资者普遍接受价格波动，但他们不想看到代币暴跌。任何加密货币的大规模代币倾销都表明代币持有者对该项目失去信心。虽然没有办法阻止有人试图在公开市场上倾销 TEA，但有一些保障措施可以防止这种情况发生。
考虑到在早期阶段，TEA代币 的挖矿收获量很小。市场上出售的挖矿获得的TEA代币不应太多。这种有限的供应将使做市商更容易购买并保持价格稳定。只要价格能保持在一个健康的水平并逐渐上涨，那些以前卖过TEA代币的人都会为自己的轻率行为感到后悔。因此，相信该项目的矿工和长期持有者可以很容易地消化这些被倾销的代币，这些倾销行为最终会在更长的时间范围内表现为昙花一现。
当然建立一个新的挖矿社区是非常困难的。 TEA 项目不会从头开始创建这样一个新社区。吸引新矿工加入的关键是利用现有的挖矿社区，通过展示 TEA 项目如何为他们带来额外的价值。例如，IPFS 矿工可以联合挖矿 FIL 和 TEA 代币。 TEA 使 IPFS 成为“Interplanetary Function as a Service”，而不仅仅是一个文件系统。 TEA dApps 需要在 IPFS 上存储代码和数据，这为 IPFS 增加了另一个落地应用。 Polkadot 和 Ethereum 等其他智能合约平台可以将其计算任务卸载到 TEA 网络。这种卸载并不是转移他们的利润；相反，它创造了更丰富的计算需求，而这些需求原本在他们的区块链上是不可行的。作为回报，更多 dApp 可以在其区块链上运行并产生更多收入。 TEA 不是试图与其他合作伙伴竞争或从其他合作伙伴那里转移利润，而是创造对所有人都有利的新用户需求。
我们应该提到，无论我们如何设计矿工经济来最初提振 TEA 代币，它仍然是一个短期解决方案。从长远来看，需要有对 TEA 代币的使用需求。 TEA 项目团队已经开始研究在 TEA 网络上运行的所谓的 Rich dApp。利用现有的 Filecoin、Polkadot 和 Ethereum 社区帮助我们期待他们在构建这个更大的生态系统方面的合作。一个例子是在IPFS节点上增加计算模块；这使 IPFS 矿工能够联合挖矿 FIL 和 TEA 代币。 dApp 还需要在 IPFS 上存储数据和代码，从而为 IPFS 带来更多实际用例。这是一个双赢的局面。

**Comment by kevingzhang** [comment]
added to tea-docs and showing here https://teaproject.org/#/doc_list/%2F%E4%B8%AD%E6%96%87%E8%B5%84%E6%96%99%2Fminer_tokenomics.md
