### ISSUE TITLE
Translate #52 to Chinese. Go to market strategy

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#60]
You can write md file under moderators or under tea-docs Chinese folder

**Comment by kevingzhang** [comment]
this is the issue #52 you can find the English scripts there

**Comment by lxm218** [comment]
如果您是第一次接触TEA 项目的新手并想了解更多信息，请单击视频右上角的链接。
 
TEA 项目拥有一个丰富、不断发展的生态系统。在该系统中，开发人员、矿工和消费者都会产生对 TEA 代币的需求。消费者需要 TEA 代币来支付云计算服务费用或消费在TApps上面的内容服务。那么为什么开发者会选择 TEA 项目作为他们的开发平台并构建 TApps呢？
 
从技术角度来看，TEA 项目让开发者及其应用程序成为通向去中心化的桥梁。大多数现有的云计算技术都可以用于 TApps 开发。开发人员可以继续使用他们最喜欢的编程语言将他们的程序编译成 Web Assembly 的格式。 **TEA 项目与硬件和软件无关的设计大大降低了开发人员的进入门槛 （The TEA Project's hardware and software-agnostic design greatly reduces any barriers to entry）。**
 
在筹集早期开发资金方面，TApp Store提供联合曲线（bonding curve)，将未来的应用收入转化为早期投资支持。这些投资者大多是 TEA 矿工和消费者，例如 TApp 策展人。这使得 TApp Store 不仅是一个应用商店，也是一个连接开发者、矿工和消费者的社区。
 
早期 TApp 投资者大部分是矿工，因为他们通过种植茶树获得TEA收益可以进行投资。精心设计的矿工经济是激励矿工将收益再投资的关键因素。 TEA 项目的抵押计划旨在鼓励早期的矿工不断地对他们的挖矿收益进行再投资。**内置激励措施包括用 TEA或Camellia进行质押，使用TEA 购买更多茶树种子都有助于维持 TEA 代币和 Camellia 代币的稀缺性 （The built-in incentives to either stake TEA or use it to buy more Camellia helps maintain the scarcity of both the TEA token and Camellia token）。**代币稀缺性会减少代币抛压并保持代币的价格稳定。如果代币价格上涨，矿工将很高兴看到他们的再投资策略积极支持 了TEA 代币价格的上涨。这成为 TEA 矿工代币经济的核心。
 
到目前为止，我们已经解释了 TEA 项目代币经济背后的设计理念，下面让我们更深入地了解 TEA 项目的早期参与者、矿工、开发者和消费者都是如何通过自身的行为来帮助稳定代币价格。
 
在 TEA 项目的第一阶段，我们专注于矿工经济。我们将推出 TEA 挖矿竞赛，以帮助证明我们的矿工代币经济的合理性。一旦我们有数据证明矿工代币经济有效，我们将开始部署主网上线，矿工即可以开始在主网上面积累加密资产。在这个阶段，矿工可以将他们挖矿收益的 TEA 代币抵押投资或购买更多的Camellia。这些抵押投资机会不会永远持续下去。当最好的抵押位置都被占用时，矿工拥有的 TEA需要有新的可以投资的地方。那时我们需要尽快进入第二阶段，以便矿工可以开始投资 TApp。
 
在第二阶段，我们将重点转移到应用程序开发人员。 TApp Store 是第二阶段的核心。它允许已收获大量 TEA 代币的矿工将投资扩展到应用程序开发。每个 TApp 的联合曲线（bonding curve)是矿工可以将他们的 TEA 代币用于投资未来杀手级应用的地方。联合曲线（bonding curve)的一个固有特征是早期投资者获得最佳投资回报率，这些早期投资者通常是开发者自己。他们可以将未来的收入转化为当下的资金池来支持项目发展。这是比过时的 ICO 模型更好的方法。 TEA 核心团队将首先引入一些 TApps 向开发人员演示联合曲线（bonding curve)筹资机制的工作原理。
 
TApps 本身不会产生收入；最终需要消费者来支持代币价格。所以现在我们进入关注消费者的第三阶段- 鼓励 TApps 开发人员开发满足消费者需求的应用程序。只有那些让消费者满意的TApps，投资者，策展人以及消费者才愿意支付。只要 TApps 有用，消费者就会将 TEA 代币支付到联合曲线（bonding curve)中作为“消费行为”来使用TApps的内容或服务。这些被支付的TEA将分配给 TApps 代币持有者，包括投资者和开发者。 **TApps 通过燃烧燃料和支持主机矿工来完成“消费行动”。（The TApps round out the "consume action" by burning fuel and supporting the host miners.）**
 
现在您可以看到TEA项目三个阶段如何相互加强。TApps 将具有与现有云应用程序质量相似的用户界面，并且有一个很大的好处：它们将在 TEA 项目的网络上分散运行。想象一下，即使只有 1% 的基于云的 Web 应用程序迁移到 TEA 项目平台……这些迁移的应用程序的市场规模将是巨大的。所以早期的 TEA 矿工、开发人员、策展人和消费者都将从中获得丰富收益。
