### ISSUE TITLE
Blog post draft: How TEA Project TApps Benefit Everyone

### ISSUE THREAD

**Issue by geopor** [tearust/moderators#61]
https://github.com/tearust/moderators/blob/main/Go_to_market_plan/How_TEA_Project_TApps_Benefit_Everyone.md

Post to **Medium**, 
distribution plan: **Reddit, Telegram, Twitter**

**Comment by geopor** [comment]
Also ties into https://github.com/tearust/moderators/issues/58

**Comment by lxm218** [comment]
see #62
