### ISSUE TITLE
Regarding How_TEA_Project_TApps_Benefit_Everyone.md

### ISSUE THREAD

**Issue by lxm218** [tearust/moderators#62]
I'd like to suggest we re-organize this article a bit:
**How the TEA Project Helps TApp Developers Gain Revenue** change to **How the TEA Project benefits TApp Developers**
This section will break into 3 parts:
1. bonding curve helps initial funding
2. bonding curve bundles all participants' benefits together - even consumer have motivation to become a curator
3. technically, TEA Project makes TApp development easier - this links to another article specialize technical part of TApp development

**Example** we can modify this example by adding bonding curve into the story
1. Photographer - uses bonding curve to get fund to take a great number of unique photos who also provides data to AI photo analyzer app
2. TApp developer - uses bonding curve to develop a AI photo analyzer app
3. Consumer - service payment goes to two bonding curve eventually.

**Comment by geopor** [comment]
https://github.com/tearust/moderators/commit/85da17e64b96e8387f8f7b203084e138c7e25b3d#diff-c20b3d19d03b3b45108705a7c4609b74890f280ccc8501526c9fd679ed75b430

I am working on the technical document, I'll add the link in about 30 minutes.

**Comment by lxm218** [comment]
My understanding this sentence **Developers will only host their apps on the TEA network if the reward is worth the effort.** is TApps can be hosted on other network, which Kevin said it's not correct. Therefore, I think 'host' is a bit misleading here. TApps is developed for TEA Project only. Maybe change 'host' to 'develop'?

**Comment by geopor** [comment]
Hi @lxm218 revised as requested. Also with further discussion with @kevingzhang made the photographer's workflow clearer.
