### ISSUE TITLE
please review the genesis exchange feature and algo design at https://github.com/tearust/moderators/blob/main/Preview%20release%20plan/Genesis%20exchange.md

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#63]
https://github.com/tearust/moderators/blob/main/Preview%20release%20plan/Genesis%20exchange.md

Please review and let me know if there is any thing missing or potential mistakes

**Comment by geopor** [comment]
I think it looks fine.

Regarding the last question,
**Does client need to pay a deposit in his tx that greater than the estimated USD amount? **

If there is slippage, the AMM can simply fail the transaction if there's not enough USD or TEA in the wallet.

**Comment by kevingzhang** [comment]
The design is approved. Please start work on the backend, then assign to @liyangwood for the front end

**Comment by raindust** [comment]
Backend has completed

**Comment by liyangwood** [comment]
done with wallet version 0.0.28
