### ISSUE TITLE
add FAQ in the teaproject repo discussion board for the mining contest

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#67]
I can list a few questions but I believe you have your own plan.  
- How are the assets evaluated?
- How do you distribute the award?
- How long is an epoch?
- Are every epoch the same?
- Why do you need ERC 20 address
- Do I need to use my email address for verification?
- After an epoch, the award is calculated to be less than 1 USDT, do I still get the award? It does not cover the ETH gas fee
- Is there any front runners? how can we start at the same time to be fair?
- is the TEA and USD in the contest real token?

**Comment by geopor** [comment]
- How are the assets evaluated?

Issue raised: https://github.com/tearust/tea-browser-wallet/issues/171

- How do you distribute the award?

At the end of each epoch, the winners will be sent a proportion of the USDT award amount in proportion to the overall asset value of all the winners: individual's total asset value / total overall asset value of all winners.

- How long is an epoch?

2 weeks.

- Is each epoch the same?

Yes.

- Why do you need my ERC20 address?

The contest awards are distributed in USDT to your ERC20 address.

- Do I need to use my email address for verification?

Yes (?)

- After an epoch, the award is calculated to be less than 1 USDT, do I still get the award? It does not cover the ETH gas fee.

- Is there any front runners? how can we start at the same time to be fair?

There will be no front running - every contestant gets alloted the same number of seeds and all contestants can begin mining & staking as soon as the epoch starts.

- Are the TEA and USD in the contest real tokens?

No, they are part of the simulation. The USDT rewards at the end of the contest are real though.

**Comment by geopor** [comment]
@kevingzhang please notify if anything in responses not correct.

**Comment by geopor** [comment]
Can you say how the winners will be selected?

**Comment by kevingzhang** [comment]
> * How are the assets evaluated?
> 
> Issue raised: [tearust/tea-browser-wallet#171](https://github.com/tearust/tea-browser-wallet/issues/171)
> 
> * How do you distribute the award?
> 
> At the end of each epoch, the winners will be sent a proportion of the USDT award amount in proportion to the overall asset value of all the winners: individual's total asset value / total overall asset value of all winners.
> 
> * How long is an epoch?
> 
> 2 weeks.


About 2 weeks. If there is major problems/bugs, we may end earlier, or extend longer.
> 
> * Is each epoch the same?
> 
> Yes.


No, We will make small changes in every epoch. Every epoch is a new starting point. We will try the best business model for miners.


> 
> * Why do you need my ERC20 address?
> 
> The contest awards are distributed in USDT to your ERC20 address.
> 
> * Do I need to use my email address for verification?
> 
> Yes an email is required for the signup form.


Add, mainly used to notify winner
> 
> * After an epoch, the award is calculated to be less than 1 USDT, do I still get the award? It does not cover the ETH gas fee.
> * Is there any front runners? how can we start at the same time to be fair?
> 
> There will be no front running - every contestant gets alloted the same number of seeds and all contestants can begin mining & staking as soon as the epoch starts.
> 
> * Are the TEA and USD in the contest real tokens?
> 
> No, they are part of the simulation. The USDT rewards at the end of the contest are real though.

**Comment by kevingzhang** [comment]
> Can you say how the winners will be selected?

I think you have explained. 

why do not you add more FAQ. I just add a few you may missed. You should have more in the FAQ. It is you who takes care this FAQ, not me.

**Comment by kevingzhang** [comment]
I do not know. but we need to tell them there is a cut off up front.

**Comment by geopor** [comment]
Ok language about cutoff has been added without specifying exact cutoff
