### ISSUE TITLE
have a zoom meeting before the contest, explain everything, AMA to the contestants

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#69]
of course, do it before the contest and after we have enough people enrolled

**Comment by geopor** [comment]
Zoom sessions for Q&A:
Wednesday, Aug 18 @ 2:30pm PDT (9:30pm GMT). English session —[Zoom link](https://us02web.zoom.us/j/88625860786?pwd=YXlPMHlhQWtiZ2w5RXlGZWtuZGtoQT09)
Wednesday, Aug 18 @ 9:00pm PDT (4am Friday Aug 20 GMT). Chinese session — [Zoom link](https://us02web.zoom.us/j/89793139928?pwd=ZEVKRFdHUmZBZHBId1lSM1J1MXdCQT09)

**Comment by geopor** [comment]
Wednesday afternoon session done :)
I will hand this issue off to @kevingzhang in preparation for the night session.
