### ISSUE TITLE
Explain: The real mining vs simulator mining

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#73]
TEA project needs the mining machine to have TPM chips and special designed NixOS. At the early stage, you cannot use your existing PC for mining although your PC already has a TPM chip on the motherboard. The first stage, AWS Nitro would be the first approved mining machine. Later cheaper IoT mining machine such as Raspberry Pi could be the second tier. 

Setting up AWS Nitro is not only complicated, but also expensive. We designed a simulator in our mining contest so that contestants do not need to bother setup and pay for the mining machine. They just click “plant”. 

In the real mining, the wallet is the same. the different happens right before you click “Plant”. There is a command line in the UI. You will need to go to your AWS Nitro machine and run such a command. Of course, you will need a lot of setup before you can run such a command. that’s why we skip for the mining contest. The setup steps will be explained in detail before we open public mining.

**Comment by geopor** [comment]
Updated: https://github.com/tearust/teaproject/wiki/FAQ:-Mining-Contest,-Preview-1/_compare/09fe820ee1659cc95f5bb20b96240a3284fd9441...38e34a3d89470c51f199e205ec4bbd107dae977e

Please check the COFFEE edits, that was never explained so I just wrote what I can make of it.
